[project]
name = "cyberpunk_insurgency"
version = "0.1.0"

[component.game]
id = "EHZHVN8JjFdVJ7Ps3e6fX9kzQQDo7u8VT3mL5X4p9n7e"

# --- Systems Mapping ---
# These must match the 'declare_id!' in your Rust code

[system.generate]
id = "C5iL81s4Fu6SnkQEfixFZpKPRQ32fqVizpotoLVTxA2n"

[system.join]
id = "3zMXokc8DYYAairrtAKZKPJZKHmWKRdj6G8bm8ZZVi9g"

[system.start]
id = "Cu8JkUA9a5msGWNChAuhBJ9PTE6FdevwHNgPyxbABkUL"

[system.command]
id = "YGKbhp7S1cCvvheyQ8rcuECKUR1SVpKpHjnqCqdP1cm"

[system.finish]
id = "HBdGPJycpHjjJ149T3RQGtQWjSC39MVpcKYF6JJvaF6e"

[system.tick]
id = "8tKAapRKPrNkxXwcArbSAnBHieYnX6M2WoTxukbCQtTa"